# Generated by Django 2.1 on 2019-08-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190818_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finance.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='top',
            field=models.IntegerField(default=10000, verbose_name='置顶参数(越小越靠顶,10000表示未发布)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.CharField(max_length=100, null=True, verbose_name='作者'),
        ),
    ]
