# Generated by Django 2.1 on 2019-08-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190818_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AddField(
            model_name='article',
            name='head',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='头条推荐'),
        ),
        migrations.AddField(
            model_name='article',
            name='scroll_head',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='滚动头条'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(0, '信托文章'), (1, '定容工具'), (2, '行业资讯')], default=0),
        ),
    ]
