# Generated by Django 2.1 on 2019-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20190824_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='beian',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='页面底部的备案号'),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config', verbose_name='顶部logo'),
        ),
        migrations.AlterField(
            model_name='config',
            name='ma1',
            field=models.ImageField(blank=True, null=True, upload_to='config', verbose_name='微信二维码1'),
        ),
        migrations.AlterField(
            model_name='config',
            name='ma2',
            field=models.ImageField(blank=True, null=True, upload_to='config', verbose_name='微信二维码2'),
        ),
        migrations.AlterField(
            model_name='config',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='页面底部的联系电话'),
        ),
        migrations.AlterField(
            model_name='config',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='页面底部的版权'),
        ),
    ]
