# Generated by Django 2.0.4 on 2019-09-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20190919_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=300, verbose_name='概要(用于搜索引擎识别,300字以内)'),
        ),
    ]
