# Generated by Django 2.0.4 on 2019-09-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_article_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='', max_length=300, verbose_name='本文关键字(用逗号隔开)'),
        ),
    ]
